version: "3.9"
services:
  webserver:
    container_name: PHP-webserver
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      # - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    # depends_on:
    #   - mysql-db
    ports:
      # - 80:80
      - 8080:80
    networks:
      - default

  # mysql-db:
  #   image: mysql:8.0
  #   container_name: db
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: lokalnybazar
  #     MYSQL_USER: dev
  #     MYSQL_PASSWORD: dev
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - default

  # mailhog:
  #   # do not use in production!
  #     image: mailhog/mailhog:latest
  #     environment:
  #       - MH_STORAGE=maildir
  #   # volumes:
  #   #   - ./docker/mailhog/maildir:/maildir:rw,delegated
  #     ports:
  #       - "8025:8025"
  #     networks:
  #     - default

  # redis:
  #   image: redis:7.2.3
  #   container_name: redis_container
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - default

networks:
  default: